services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: meetings
      POSTGRES_USER: meetings
      POSTGRES_PASSWORD: meetings
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: meetings
      DB_PASSWORD: meetings
      DB_NAME: meetings
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BITRIX_DEV_MODE: "true"
      CORS_ORIGIN: "*"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/usr/share/nginx/html
    command: ["sh", "-c", "cp -r /out/* /usr/share/nginx/html 2>/dev/null || true; tail -f /dev/null"]
    depends_on:
      - backend

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
  redisdata:
  frontend_build: