services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: meetings
      DB_USERNAME: meetings
      DB_PASSWORD: meetings
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BITRIX_DEV_MODE: "true"
      BITRIX_REST_URL: "https://bitrix24.newhc.by/rest/15/qx461meaiqb86ff5"
      CORS_ORIGIN: "http://localhost:5173"
    command: npm run dev
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules

  frontend:
    image: node:20
    working_dir: /app
    command: sh -c "npm ci && VITE_API_PROXY_TARGET=http://backend:4000 npm run dev -- --host --port 5174"
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_PROXY_TARGET: http://backend:4000

  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: bookmeeting_pgdata


